import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { geistSans, geistMono } from "@/fonts";

export const metadata: Metadata = {
  title: "Brainlens Starter Kit",
  description: "Generated by brainlens starter kit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("antialiased", geistSans.variable, geistMono.variable)}
      >
        {children}
      </body>
    </html>
  );
}
