import type { Metadata } from "next";
import "./globals.css";
import { fontIqos, fontIqosBreathing } from "@/fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
	title: "Brainlens Starter Kit",
	description: "Generated by brainlens starter kit",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"antialiased",
					fontIqos.variable,
					fontIqosBreathing.variable,
				)}
			>
				<div
					className="w-full h-screen flex flex-col items-center 
				bg-[url(/bg-tottem-info.webp)] bg-cover bg-center text-white"
				>
					{children}
				</div>
			</body>
		</html>
	);
}
